### PR TITLE
Adding new method for render + new devices support

### PR DESCRIPTION
**Pull request by sam-dumont**
Memory usage was quite high with the custom fonts + the layout system so here is a new render fully using the dc calls.

This allows to keep the DF way under the 28KB limit that is applied to most watches DF (even on the latest like the Enduro)

Render is not pixel perfect but quite okay, here are a few screenshots in the simulator. I can't test in real life but it should be okay.

I rearranged the layouts so the lap power is central. I had to tweak a bit the sizing to keep the fields readable so it's not symmetric anymore, but I don't think we're here to make art 🎨 

Screenshot 2021-04-14 at 15 58 14
Screenshot 2021-04-14 at 15 56 51
Screenshot 2021-04-14 at 15 52 09
Screenshot 2021-04-14 at 15 51 39
Screenshot 2021-04-14 at 15 50 46
Screenshot 2021-04-14 at 15 50 15

### CODE REVIEW

**Comment by sam-dumont** [comment]
Also, some watches do not look like they support power, we get "0" in the simulator. I did not find info on Garmin's website, not sure if every watch supporting 3.2 is able to get the power 🤔

**Comment by tommyvdz** [comment]
> Also, some watches do not look like they support power, we get "0" in the simulator. I did not find info on Garmin's website, not sure if every watch supporting 3.2 is able to get the power 🤔

Indeed, that’s what I mentioned: besides connectiq 3.2 they need support for power meter sensors, as you need to pair stryd as a power meter for the datafield to pick up power as a value. That means only the ‘multi-sports’ watches are supported, such as 745, 945, Fenix 5 plus, 6, MARQ, Enduro etc.

**Comment by sam-dumont** [comment]
Okay so I'll adapt my PR to remove devices that will not support multisport. I took my watch this morning on a run and it's very readable (background colors definitely helps get a sense on how things are going without looking at the exact number). No crashes, no issues, everything fine :D

**Comment by tommyvdz** [comment]
Nice. I've loaded the build from this branch on my device, will take it for a run today. If that works fine, and after your update to remove unsupported devices I'll release it to CIQ Store.

**Comment by sam-dumont** [comment]
Devices that are not supported are removed and I added a small change for the distance field : it will display the decimal part in a smaller font to gain a bit of space (this could also be an option, I just realize it)

new_distance

**Comment by sam-dumont** [comment]
Also, forgot to mention : I created a pipeline to release versions. So if you create a release (let's say 1.0.1) like here https://github.com/samueldumont/RunPowerWorkout/releases/tag/0.0.1 it will generate the artifacts and set the proper version in the manifest. Will be easier to release in the connectIQ store.

**Review by tommyvdz — APPROVED** [review]
I just came back from a run with this version, everything worked perfectly. Thanks!

**Pull request merged**
